### ISSUE TITLE
use http proxy to access one website,it randomly appear 502 Bad Gateway 

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#147]
OS: Centos 6.5 64bit
3proxy 0.8.9
Problem:    Use http proxy to access one website,it randomly appears "502 Bad Gateway Host Not Found or connection failed" serveral times in one day.The error will exist for 5-20 minutes,then it become 200 code again.Every day has 502 bad gateway for several times.It's confirm when 502 appears,the website is working and access the other websites are also working.

When 502 bad gateway,the log output error code 00013 .  Any suggestion?

**Comment by z3APA3A** [comment]
0013 means connect fails to target. The reasons may be different and depends on system, configuration and load, e.g. sytem fails to allocate ephemeral port, you can try to perform connect with telnet to target host and confirm the problem is not in the proxy itself. There can also be networking problem. You can start with extending ephemeral port range and monitoring reachability of remote hosts from the proxy.

**Comment by raintears2** [comment]
I have add one  nsrecord for the website point to ip 1.1.1.1 , then reload the 3proxy,but I check the log,it still resolve the website with its original ip, not the setting 1.1.1.1,how to config it?

nserver 223.5.5.5
nserver 223.6.6.6
nsrecord   www.example.com  1.1.1.1
nscache 65536

timeouts 1 5 30 60 180 1800 15 60
users $/root/3proxypassword
monitor /root/3proxypassword
maxconn 90000

**Comment by z3APA3A** [comment]
nsrecord must be after nscache

**Comment by kodmanyagha** [comment]
this problem still continue. I'm using version 0.8.6. I tried in centos 7 and ubuntu 18 and I'm getting 502 errors randomly. I'm looking to source codes but this will get long time for me to find the problem. Please help us. Thanks.

**Comment by z3APA3A** [comment]
what do you have in logs?
