### ISSUE TITLE
Sending chosen parent proxy in response header

### ISSUE THREAD

**Issue by israelidanny** [z3APA3A/3proxy#170]
It is extremely useful for my needs to know which parent proxy was chosen for any specific request. 

Is there any way to send that info back with a response, using either core functionality, plugins?

If a plugin doesn't exist, how would one approach the task of writing a plugin that adds a header to the response that specifies which parent proxy (IP and port) was used?

**Comment by z3APA3A** [comment]
This task is not solvable in the general case, and I see no reason to implement it in http proxy, because most servers currently use https, and it's impossible to tamper the response header in https without certificate spoofing.

Use SOCKSv5 which is more appropriate for the task like this, SOCKSv5 reply contains an information about external IP:port.

**Comment by israelidanny** [comment]
Alright, the question is - can I configure 3proxy in such a way that the client connecting to it would know what the external IP:port of the parent that was used is?

**Comment by z3APA3A** [comment]
You do not need any special configuration, if you use SOCKSv5 this information already presents in server's reply, see
https://www.ietf.org/rfc/rfc1928.txt
