### ISSUE TITLE
3proxy connect-back

### ISSUE THREAD

**Issue by Greynad** [z3APA3A/3proxy#250]
Hello,
I would like to use 3proxy in a similar way to rpivot.py. My understanding is that you can with this kind of setup:
computer A which is behind a NAT/firewall and doesn't have a public ip address.
computer B which has a public ip address.

Computer B starts a connect-back server
`socks -R0.0.0.0:1234 -p1080`

Computer A connects back to it
`socks -r10.10.10.11:1234`

Unfortunately, I've been struggling to get this to work, I'd like to connect to 127.0.0.1:1080 on computer B and get access to the network where computer A lives. Maybe I'm misunderstanding something

Many thanks

**Comment by z3APA3A** [comment]
No, this way you have socks connecting to socks. Client connect to first socks and sends e.g. http request, this request comes to second socks server and fails, because socks server expects socks and gets http.

Do exactly as How To says
https://3proxy.ru/howtoe.asp#CONNBACK
with 'socks' instead of 'proxy'
that is, you run 'socks' as a connect back client (behind the nat), and 'tcppm' as a connect back server (accessible from the client).
Client connect to tcppm, tcppm forwards connection to proxy via connect back to socks and socks processes socks request from the client.
