### ISSUE TITLE
nmake /f Makefile.msvc64  error in vs2017

### ISSUE THREAD

**Issue by gitlsl** [z3APA3A/3proxy#270]
LINK : fatal error LNK1104: can not open “../bin64/3proxy.exe”
follow your step just unzip source, and run nmake /f Makefile.msvc64   got above error

**Comment by z3APA3A** [comment]
Probably, you have launched 3proxy.exe from bin64 folder and linker can not overwrite 3proxy.exe because it's locked. Stop 3proxy, copy 3proxy.exe to different folder and launch executable from different folder. Also, it may be a result of antivirus blocking the executable, because some antivirial programs detect self-compiled proxy as potentially unwanted software or even backdoor (due to fact 3proxy or some parts of it's code can often be found on compromised hosts), in this case add the path to exclusion in antivirus setttings.

**Comment by gitlsl** [comment]
I think it's due to no `libeay32MT.lib ssleay32MT.lib` upload to the source      so 3proxy.exe can not build suceess?

**Comment by z3APA3A** [comment]
Error above is not result of any compilation/linking issue, it's clearly the problem accessing the file on the disk.

**Comment by hamperfait** [comment]
I'm having the same issue. I am not running 3proxy at all (and the .exe I have is not in bin64 folder, not bin either), but when I compile it I get the same error.

I have tried stopping the AV but it won't work either... I even tried doing it with Administrator rights console, but none of it works and I always get the same error.
I tried on a VM with all dependencies and no 3proxy and it still wouldn't work
