### ISSUE TITLE
SSLPlugin do not compiles (stock Ubuntu 18.04)

### ISSUE THREAD

**Issue by Sfinx** [z3APA3A/3proxy#280]
```
make[2]: Entering directory '/xyz/socks5/3proxy/src/plugins/SSLPlugin'
gcc -fpic -g -O2 -fno-strict-aliasing -c -pthread -DWITHSPLICE -DGETHOSTBYNAME_R -D_THREAD_SAFE -D_REENTRANT -DNOODBC -DWITH_STD_MALLOC -DFD_SETSIZE=4096 -DWITH_POLL -DWITH_NETFILTER my_ssl.c
my_ssl.c: In function Б─≤ssl_copy_certБ─≥:
my_ssl.c:118:37: error: dereferencing pointer to incomplete type Б─≤X509 {aka struct x509_st}Б─≥
  char hash_name_sha1[sizeof(src_cert->sha1_hash)*2 + 1];
                                     ^~
Makefile.inc:9: recipe for target 'my_ssl.o' failed
make[2]: *** [my_ssl.o] Error 1
```

**Comment by z3APA3A** [comment]
Make sure "libssl-dev" package is installed.

**Comment by Sfinx** [comment]
Sure it is installed, seems like you never compiled it by yourself at 18.04 - the 1.1.0g version it uses do not contains the x509_st struct anymore.

**Comment by z3APA3A** [comment]
Yes, SSLPlugin is not default for linux. I've never compiled it with 1.1.0 and I have no plans to even try before 1.1.1 or so due to issues like
https://github.com/openssl/openssl/issues/2124
So the answer is - use OpenSSL 1.0.

**Comment by Sfinx** [comment]
Do not think that OpenSSL will be ever rewritten due to not mature software that are not able to support Linux by default like your as OpenSSL was written for Linux ;) So the right answer - do not use such software

**Comment by z3APA3A** [comment]
You misunderstand this reply. Currently, 1.1 version is unstable and a lot of 1.0 functionality is simply missing. It's replaced with some incomplete and purely engineered quick patches instead of providing solid and comprehensive API. Specification changes from version to version without either planning or even changes in documentation. And this situation is a classic description of how OpenSSL develops for ages. I see no reason to port the code to 1.1 for a while, because it will require further support for every new OpenSSL version, giving the fact SSLPlugin is non-default and rarely used I prefer to spend the time in more useful manner before 1.1 specification more or less finalized. So I hope there will be something like 1.1.1 to finalize the standard. It doesn't change the fact OpenSSL is awful, so there is a high chance I will switch to LbreSSL or BoringSSL.

P.S.
OpenSSL has nothing to do with (GNU) Linux, it's provided under BSD-style license.

**Comment by Sfinx** [comment]
You have been misunderstood my reply:  people will not use software which can't support out of the box at least two major Linux LTS distros [ currently Ubuntu 18.04 & Debian Stretch ] which despite your claims about OpenSSL quality use exactly the 1.1.x version of it. So all apps inside them.

P.S. The project software license has no relation to its development history and major usage area - the SSLeay (forked to OpenSSL at 1998) was targeted for Linux, all the FTP release packages were made for RedHat and Debian only.

**Comment by Bo0oM** [comment]
@Sfinx You have not solved this problem?

I tried to install an old version of openssl (OpenSSL 1.0.2l  25 May 2017)
Installed Debian 9 to try to fix this bug. But nowhere is it going to be correct.

**Comment by Bo0oM** [comment]
Problem solved

apt-cache policy libssl-dev
&
apt-get install libssl-dev=version-from-apt-cache-1.0.2

**Comment by Sfinx** [comment]
No, this project appeared useless for my task mostly by its dumb developer but SSLproxy fitted ideal
