### ISSUE TITLE
3proxy high memory usage 

### ISSUE THREAD

**Issue by timonty001** [z3APA3A/3proxy#317]
Running 3proxy 0.8.12 with following config

daemon
nserver 208.67.222.222
nserver 208.67.220.220
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
auth iponly
allow * xx.xx.xx.xx
parent 1000 http ipv6 85
proxy -p81 -a -6 -iipv4 -eipv6

Memory usage 66.96 Mb /usr/local/3proxy/3proxy /usr/local/3proxy/3proxy.cfg just on starting proxy and
memory usage  259.06 Mb /usr/local/3proxy/3proxy /usr/local/3proxy/3proxy.cfg when a connection is made . 
is above memory usage normal ?

**Comment by z3APA3A** [comment]
It depends on what is "memory usage" (vritual memory? Commited memory? physical memory?) and how memory grows after. 
In general, change in consumption of physical memory in the begging is OK, because pages from executable/shared library are dynamically loaded on-the-run and some internal structures are initialized on the first use of different libc / (system) API functions.
I can't say if growing from 66 to 260 is OK, it depends on huge number of paramters (OS, memory type, libc and system libraries versions, system configuration, network configuration, another applications running with same shared libraries, , etc).
