### ISSUE TITLE
How to configure user authorization on parent proxy?

### ISSUE THREAD

**Issue by spiller1975** [z3APA3A/3proxy#368]
I need to authorize users on the second proxy server.
It is necessary that the first proxy server simply passed traffic through itself without authorization.
However, I need to use the parent command.

I'd like do like this for balancing traffic:
auth iponly
allow *
parent 250 http 172.16.100.1 3128
parent 250 http 172.16.100.2 3128
parent 250 http 172.16.100.3 3128
parent 200 http 172.16.100.4 3128

All adrresses 172.16.100.1 - 172.16.100.4 configured on the next proxy.
User authorization must occur on this proxy.

Tell me whether this can be implemented?

**Comment by z3APA3A** [comment]
See 'parent' command description in manual, it depends on what exactly do you want from 3proxy.
There are at least 3 different ways:
1. configure login/password in 'parent'
2. use '*' instead of login/password in 'parent' + 'socks' or 'proxy' to request login and password from user and pass it to parent proxy
3. use tcppm instead of 'socks'/'proxy'to perform balancing on TCP level without parsing any requests, authentication will be requested from client directly by parent proxy.
