### ISSUE TITLE
What are clientparam structure fields stands for?

### ISSUE THREAD

**Issue by VasiliPupkin256** [z3APA3A/3proxy#493]
I'm reading the sock proxy code and wondering what `sincl`, `sincr`, `sinsl`, `sinsr` fields stands for.

On the line https://github.com/z3APA3A/3proxy/blob/3b5fa46e27119a282b456f3aee84a537d4c6e862/src/socks.c#L219 the field `sincr` is used before initialization. On the line https://github.com/z3APA3A/3proxy/blob/3b5fa46e27119a282b456f3aee84a537d4c6e862/src/socks.c#L331 field `sinsr` is assigned to the `req` filed (which stands for DST field of the client request) but then the datagram received from the client is tested against `sincr` not `sinsr`. Isn't it `sincr` should be assigned to `req` then?
On the line https://github.com/z3APA3A/3proxy/blob/3b5fa46e27119a282b456f3aee84a537d4c6e862/src/socks.c#L425 the data is sent to the address `sin` which is not yet initialized (in the current loop iteration) and it should probably be sent to `sincr` which as I understand should stand for "Socket INternet Client Remote" or something like that...

**Comment by z3APA3A** [comment]
sinsr = socckadr_in (proxy) to server remote
sinsl = socckadr_in (proxy) to server local
sincr = socckadr_in (proxy) to client remote
sincl = socckadr_in (proxy) to client local

> the field sincr is used before initialization. On the line 

param is always initialised, sincr initially contains client information from control connection:

https://github.com/z3APA3A/3proxy/blob/3b5fa46e27119a282b456f3aee84a537d4c6e862/src/proxymain.c#L702

https://github.com/z3APA3A/3proxy/blob/3b5fa46e27119a282b456f3aee84a537d4c6e862/src/proxymain.c#L773

> field sinsr is assigned to the req filed (which stands for DST field of the client request) but then the datagram received from the client is tested against sincr not sinsr. Isn't it sincr should be assigned to req then?

> the data is sent to the address sin which is not yet initialized (in the current loop iteration) and it should probably be sent to sincr

I will check it, thanks. Probably I'm currently using information from control connection + from datagram received rather than information from UDP association request and it's better to be changed.

**Comment by VasiliPupkin256** [comment]
In UDP association mode the DST field (i.e. `param ->req`) is equivalent to `sincr` then. Client is sending datagrams from DST.ADDR to the server and server shall route datagrams received on remote socket to the `sincr` then. Right?

**Comment by z3APA3A** [comment]
I checked implementation and see no issues. 

>field sinsr is assigned to the req filed (which stands for DST field of the client request) but then the datagram received from the client is tested against sincr not sinsr

Client UDP ASSOCIATE request contains IP address of the destination client is planning to reach, it's useful to choose an external IP and protocol famil,

```
                                                                          The DST.ADDR and
   DST.PORT fields contain the address and port that the client expects
   to use to send UDP datagrams on for the association.  The server MAY
   use this information to limit access to the association.  If the
   client is not in possesion of the information at the time of the UDP
   ASSOCIATE, the client MUST use a port number and address of all
   zeros.

```
 so
param->sinsr = param->req; 
is correct. 

>the data is sent to the address sin which is not yet initialized (in the current loop iteration) and it should probably be sent to sincr which as I understand should stand for "Socket INternet Client Remote" or something like that...

Unfortunetely, there is no way to get the client port before the UDP datagram from the client is request. As it's received, sin contains the address of the remote client UDP socket. sincr contains address of TCP connection, it can not be used to send a datagram. I've added
`				sin = param->sincr;
`
initialization, it may allow client to receive the datagram from proxy before any datagram send assuming the same port number is used for TCP and UDP ports and prevents connection termination due to send failure. I doubt any client does it though.
3proxy requires client to use same IP address for both control connections and UDP datagrams for security reasons.

**Comment by z3APA3A** [comment]
Though, actuall, RFC is very unclear for this case (at least on my English level), if you have practical examples of client implementations I can correct it.

**Comment by VasiliPupkin256** [comment]
Well, the author of RFC has the github profile @patchvonbraun and we may ask him for clarification. 

But it doesn't matter, this confusing statement is already interpreted differently by many programmers https://stackoverflow.com/a/62332181 https://github.com/ginuerzh/gost/issues/96 etc, and multiple software was written that interpret DST field both ways, as a client address and as a remote address. Hence the field should probably be ignored by the proxy completely, and it is indeed ignoring it now, because an assignment `param->sinsr = param->req` is not used to filter remote addresses and is overwritten later in the code.
