### ISSUE TITLE
After restart it does not working

### ISSUE THREAD

**Issue by RaminAT** [z3APA3A/3proxy#575]
The proxy is not working if we install according to README file and when reboot the server. We need to run this command and restart the server in order to work:

`find /etc/ -type f -readable -writable -exec sed -i "s/\/var\/run\/3proxy\/3proxy.pid/\/tmp\/3proxy.pid/g" {} \;`

**Comment by z3APA3A** [comment]
Probably, you're using systemd-based Linux distribution, update to 0.9.3 version or manually fix /usr/lib/systemd/system/3proxy.service file by removing the trailing "&" from ExecStart command, it was fixed with this commit:

https://github.com/z3APA3A/3proxy/commit/07603ceea7904479b158c6d800034d405f31540d
