### ISSUE TITLE
Segmentation fault on CentOS 7

### ISSUE THREAD

**Issue by minhdv92** [z3APA3A/3proxy#577]
Hello.

I installed an run with command:

socks -p2020 -ixxxx -eyyyyy -osTCP_NODELAY -ocTCP_NODELAY -S8192 -6

I'm set socks5 on firefox and goto google.com is ok, but when I go to other website the proxy will be Segmentation fault

Anyone can tell me why?

Thanks

**Comment by z3APA3A** [comment]
What is proxy version you use?

**Comment by minhdv92** [comment]
I used "socks of 3proxy-0.9.3 ()"

**Comment by z3APA3A** [comment]
`-S8192` is too small stack amount to use with default resolver. Probably, you do not need -S option at all, unless you clearly know what do you need it for.

**Comment by minhdv92** [comment]
I tried without -S8192 and got same problem

**Comment by z3APA3A** [comment]
Try to do the next:
1. check you are really using the latest version by running socks -v
2. provide the segmentation fault message, check it for instruction pointer (ip) address 
3. try to run `addr2line -e /path/to/socks -C -f 0xaabbccdd` with address found in previous step

**Comment by minhdv92** [comment]
I used version 0.9.3
This tools stopped only message "Segmentation fault"

![Capture](https://user-images.githubusercontent.com/77137924/104006913-be74a280-51d9-11eb-99e4-1076b6918b41.PNG)

**Comment by z3APA3A** [comment]
Check /var/log/messages

**Comment by minhdv92** [comment]
Here

![new](https://user-images.githubusercontent.com/77137924/104011376-93da1800-51e0-11eb-968f-a059339add49.PNG)

**Comment by z3APA3A** [comment]
These crashes are older and are probably stack related, it seems like a result of running with -S8192. Do you have newer ones? Or you can try to run with a large stack size, e.g.
-S262144

or even better is to run socks under gdb

gdb socks
(in gdb) run -p2020 -i... -e...

**Comment by minhdv92** [comment]
I tried a new one and with -S262144
![new](https://user-images.githubusercontent.com/77137924/104013217-c20d2700-51e3-11eb-8a86-740b7ebdd46d.PNG)

And with gdb

![gdb](https://user-images.githubusercontent.com/77137924/104013240-c89b9e80-51e3-11eb-8901-9364921b9263.PNG)

**Comment by z3APA3A** [comment]
In short: this problem happens in GetAddrInfo (name resolution function).
By default 3proxy uses system name resolver, and glibc allows different dynamics extensions to this resolver. Some of extensions are purely written and either misuse a stack or are not thread-safe or both. I can't reproduce this issue with official CentOS docker, probably you've installed some package which affects name resolution, e.g. one with local name cache, DNS over HTTP, etc. But, even default resolver is known to have race conditions on sophisticated configurations. This issue is explained here: https://3proxy.ru/highload.asp
There are few options:

1. Try to identify and remove or replace resolver extension
2. You can try to experiment with stack size, e.g. set one to 10MB (10485760), and, if it works, you can try to find a smaller stack size which works for you.
3. Use 3proxy binary instead of socks binary and configure nserver / nscache / nscache6. If nserver is configured, 3proxy uses it's own resolver.

**Comment by minhdv92** [comment]
This server I installed squid proxy. I think this is problem.

I tried on other server and it working.
Thank for your support

**Comment by ValdikSS** [comment]
@z3APA3A default thread stack size (of 65536 total) is not enough for .local mdns resolution on Fedora 34. It crashes in nss-mdns library, in `verify_name_allowed_with_soa` or `local_soa` functions.

By default, `conf.stacksize` is 0 and default thread stack size is `PTHREAD_STACK_MIN + (32768+conf.stacksize)` (which is 65536 at least on my system).

Consider increasing stack size. Settings `-S32768` (additional 32768 bytes) seem to work fine.
