### ISSUE TITLE
I got the error message 00013 and 00012.

### ISSUE THREAD

**Issue by hiclaim** [z3APA3A/3proxy#582]
Hello currently I am using 3proxy version 0.9 but when there are some proxies I am using and error code [00013, 00012].
I spent 14 hours fixing it but it didn't work. I want to ask if there is any way to fix it.
Thanks
![HTTP](https://user-images.githubusercontent.com/44727524/104860244-05426500-595d-11eb-84e0-e6375566be9b.png)

**Comment by z3APA3A** [comment]
12 means external IP is incorrect and can not be assigned, see https://3proxy.ru/howtoe.asp#INTEXT. Also, it may bethe lack of ephemeral ports, see https://3proxy.ru/highload.asp
13 means you can not connect to destination host, probably because routing is not configured. Check with
ping6 -S configured_external_address destination_address
