### ISSUE TITLE
Add 1 backup network when the primary network loses the network

### ISSUE THREAD

**Issue by shally-vn** [z3APA3A/3proxy#590]
My computer has more than 1 network. I want to configure the main network when it fails it will move to the backup network.
i hope someone can help me, i thanks a lot

**Comment by z3APA3A** [comment]
There is no way for proxy to check the condition "main network fails" because proxy knows nothing about your networking and it's conditions. The only thing proxy can do is to attempt to retry the connection with some different settings, but it may be problematic, depending on the failure kind, e.g. in the case of timeout client will not wait for proxy to make different connections. The best thing you can do is to make a script which will either handle you interface up/down or periodically check for network conditions and switch the proxy configuration accordingly.
