### ISSUE TITLE
socks remove X-Forwarded-For header

### ISSUE THREAD

**Issue by qcybb** [z3APA3A/3proxy#617]
How can we remove the X-Forwarded-For header when using socks?

I've tried the -a switch and that did nothing.

**Comment by z3APA3A** [comment]
socks proxy knows nothing about http and does not change http headers in any way. You can redirect HTTP traffic from socks to HTTP proxy if you need to strip this header. As an alternative, you can try to use PCREPlugin to strip X-Forwarded-For from client data (not client header, because http data for socks is application data).

**Comment by qcybb** [comment]
Thank you.
